services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ostrich
      POSTGRES_PASSWORD: ostrich
      POSTGRES_DB: test1
