name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create and activate virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Initialize dependencies
        run: |
          pip install -r requirements.txt
      - name: Test API login user
        run: |          
          pytest test/test_user.py
      - name: Test API endpoints
        run: |          
          pytest test/test_weather.py
